SET SQL DIALECT 3;
CREATE DATABASE 'C:\fbtest\smoke.fdb'
    USER 'SYSDBA' PASSWORD 'masterkey'
    DEFAULT CHARACTER SET UTF8;
COMMIT;

CREATE TABLE EMPLOYEE (
    EMP_ID    INTEGER NOT NULL PRIMARY KEY,
    EMP_NAME  VARCHAR(60) NOT NULL,
    DEPT_NO   VARCHAR(3),
    SALARY    NUMERIC(10,2),
    HIRE_DATE DATE,
    ACTIVE    BOOLEAN,
    NOTE      BLOB SUB_TYPE 1
);
COMMIT;

INSERT INTO EMPLOYEE VALUES (1, 'Alice Andersson', '600', 75000.50, DATE '2020-03-15', TRUE,  'Senior developer');
INSERT INTO EMPLOYEE VALUES (2, 'Bob Brown',       '600', 82500.00, DATE '2019-07-01', TRUE,  NULL);
INSERT INTO EMPLOYEE VALUES (3, 'Carlos Chen',     '900', 65000.75, DATE '2022-11-20', FALSE, 'On leave');
INSERT INTO EMPLOYEE VALUES (4, 'Diana Davis',     '600', 98000.25, DATE '2018-01-10', TRUE,  'Team lead');
INSERT INTO EMPLOYEE VALUES (5, 'Erik Eklund',     '700', 71200.00, DATE '2021-06-30', TRUE,  NULL);
COMMIT;

CREATE TABLE FILE_STORAGE (
    FILE_ID  INTEGER NOT NULL PRIMARY KEY,
    NAME     VARCHAR(40) NOT NULL,
    SIZE_B   INTEGER NOT NULL,
    PAYLOAD  BLOB SUB_TYPE 0
);
COMMIT;

INSERT INTO FILE_STORAGE VALUES (1, 'logo.png',     6, CAST(_ASCII'binary' AS BLOB SUB_TYPE 0));
INSERT INTO FILE_STORAGE VALUES (2, 'empty.dat',    0, NULL);
INSERT INTO FILE_STORAGE VALUES (3, 'document.bin', 5, CAST(_ASCII'hello'  AS BLOB SUB_TYPE 0));
COMMIT;

CREATE OR ALTER VIEW V_ACTIVE_EMP (EMP_ID, EMP_NAME, DEPT_NO) AS
    SELECT EMP_ID, EMP_NAME, DEPT_NO
      FROM EMPLOYEE WHERE ACTIVE = TRUE;
COMMIT;

CREATE TABLE TQUOTES (
    ID    INTEGER NOT NULL PRIMARY KEY,
    LABEL VARCHAR(60) NOT NULL
);
COMMIT;

INSERT INTO TQUOTES VALUES (1, 'D''Agua');
INSERT INTO TQUOTES VALUES (2, 'O''Brien & Co');
COMMIT;

CREATE TABLE TPK_COMPOSITE (
    A     INTEGER NOT NULL,
    B     INTEGER NOT NULL,
    LABEL VARCHAR(20),
    CONSTRAINT PK_TPK_COMPOSITE PRIMARY KEY (A, B)
);
COMMIT;
QUIT;
